### ISSUE TITLE
Does this container allow for custom skins and extension?

### ISSUE THREAD

**Issue by lordratner** [felddy/weewx-docker#108]
I'm just trying to get a better idea of whether this will allow for more than just changing the base config file. 

For example, if I want to use the Belchertown skin and Phrenology extension, can I do that in this container? It would only require adding volume mappings for /usr/share/weewx/user and /etc/weewx/skins. Maybe a couple others for the extensions too.

Thoughts?

**Comment by jmerifjKriwe** [comment]
@lordratner have you tried? If so, could you give me a hint how to do it?
