### ISSUE TITLE
Add InfluxDB plugin

### ISSUE THREAD

**Issue by pgolawsk** [felddy/weewx-docker#284]
# 💡 Summary #

I would like to have this docker image with weewx-influxdb plugin installed.

## Motivation and context ##

I use InfluxDB in addition to SQLite, so it's easier to visualize my weather data via Grafana, along with other sensor metrics I store on InfluxDB.

## Implementation notes ##

Since the docker image have already 2 plugins for weewx then I hope that would not be a big deal to include it.
No need to modify weewx.conf, since I can easily read plugin docs and add it myself.
Just add this to dokcerfile with a few more commands t actually install it.
wget -O weewx-influx.zip https://github.com/matthewwall/weewx-influx/archive/master.zip

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Adjusted weewx.conf file with InfluxDB setup is active

**Comment by felddy** [comment]
With the release of `v5` I've moved away from pre-installing extensions in the container as the migration of the WeeWX project to `pip` has made library management easier.   With the new container you just need to run:

```shell
docker compose run --rm weewx \
  extension install --yes \
  https://github.com/matthewwall/weewx-influx/archive/master.zip
 ```

See:
- https://github.com/felddy/weewx-docker?tab=readme-ov-file#installing-weewx-extensions
