### ISSUE TITLE
Is there way to install custom drivers?

### ISSUE THREAD

**Issue by LMSSonos** [felddy/weewx-docker#39]
# 💬 Questions and Help

I was looking to install a custom driver: https://github.com/michael-slx/weewx-weatherlink-live - is there a way to make this persistent?

**Comment by LMSSonos** [comment]
built my own image based on yours ;-) in case someone interested

```
RUN apt-get install -y wget
RUN wget -O weewx-weatherlink-live.tar.xz https://github.com/michael-slx/weewx-weatherlink-live/releases/download/v1.0.10/weewx-weatherlink-live-v1.0.10.tar.xz
RUN ./bin/wee_extension --install=weewx-weatherlink-live.tar.xz
RUN pip3 install requests
RUN pip install --no-cache wheel setuptools
RUN pip install --no-cache configobj paho-mqtt pyserial pyusb
RUN pip install --no-cache Cheetah3
RUN pip install --no-cache Pillow

```

**Comment by Daniel-WW** [comment]
Hi,
Im searching for a way, how to install the belchertown skin an the MQTTSubscribe extension.

I’m a quiet newbie in Github and Docker stuff and so I want to ask, if you cold explain, how you did modify the docker image.

I’m using visual studio code and in my imagination and planing, i was thinking about to fork the existing code, modify the extensions and bring it to run on may docker stack. But how could I do that? What are the first steps? Do I have to upload the code to hub.docker.com?

As you see, I would be grateful for every kind of help?
Maybe you could link a useful tutorial or some other advices?

Thanks in advance and best regards - Daniel

**Comment by LMSSonos** [comment]
@Daniel-WW see here how to start with docker on your local pc, you can do all locally and don't need docker.com - https://code.visualstudio.com/docs/remote/containers#_getting-started
