### ISSUE TITLE
v4 support

### ISSUE THREAD

**Issue by ruudboon** [felddy/weewx-docker#9]
Thnx for this container! Any plans for adding v4 support?

**Comment by felddy** [comment]
Absolutely.  I'll try to add it today.

**Comment by felddy** [comment]
I've published a pre-release version of the container: `v4.0.0-pre.1`

https://github.com/felddy/weewx-docker/releases/tag/v4.0.0-pre.1

I'm currently testing it on my weather station and watching the logs.  If everything continues to look good I'll publish the `v4.0.0` release in an hour or two.

**Comment by ruudboon** [comment]
This is awesome! Thnx

**Comment by ruudboon** [comment]
Would it be possible to add the mqtt plugin by default? I’m extending your container now.

**Comment by felddy** [comment]
The testing was without issue.  I've published the final version of v4.0.0 to docker hub.   Please open up another issue with the MQTT request.  

https://github.com/felddy/weewx-docker/releases/tag/v4.0.0
